### ISSUE TITLE
Boot loop on Raspberry Pi 8GB

### ISSUE THREAD

**Issue by frezbo** [talos-systems/talos#3270]
## Bug Report

Boot loop on Raspbeery Pi 8GB

### Description

U-boot fails to boot and keeps on resetting when trying to boot from USB (the same version works from an SD card)

### Logs

```shell
U-Boot 2021.01 (Feb 20 2021 - 17:41:55 +0000)

DRAM:  7.9 GiB
RPI 4 Model B (0xd03114)
MMC:   mmcnr@7e300000: 1, emmc2@7e340000: 0
Loading Environment from FAT... Card did not respond to voltage select! : -110
In:    serial
Out:   vidconsole
Err:   vidconsole
Net:   eth0: ethernet@7d580000
PCIe BRCM: link up, 5.0 Gbps x1 (SSC)
starting USB...
Bus xhci_pci: probe failed, error -110
No working controllers found
Hit any key to stop autoboot:  0 
"Synchronous Abort" handler, esr 0x96000044
elr: 000000000009c1a4 lr : 0000000000091af4 (reloc)
elr: 000000003b2751a4 lr : 000000003b26aaf4
x0 : 0000000000000a30 x1 : 0000000000000a60
x2 : 702d616d642d6465 x3 : 7261687300000000
x4 : 1000000003000000 x5 : 000000000000005c
x6 : 000000003b2d32d0 x7 : 1000000002ffffd0
x8 : fffffffffffffff0 x9 : 0000000000000008
x10: 00000000ffffffd0 x11: 000000000000000a
x12: 0000000000000006 x13: 000000000001869f
x14: 000000003ae48ba0 x15: 0000000000000002
x16: 000000003b277248 x17: 99f7de22808e8223
x18: 000000003ae54da0 x19: 0000000000000031
x20: 000000003b2d2d10 x21: 000000003b2e5000
x22: 0000000000000005 x23: 000000000000000a
x24: 0000000000000000 x25: 000000003b2e5000
x26: 0000000000000000 x27: 000000003b2c74d1
x28: 000000003b2bd000 x29: 000000003ae47d10

Code: a9410803 8b130001 b2400273 f9000413 (f9000c62) 
Resetting CPU ...

resetting ...


U-Boot 2021.01 (Feb 20 2021 - 17:41:55 +0000)

DRAM:  7.9 GiB
RPI 4 Model B (0xd03114)
MMC:   mmcnr@7e300000: 1, emmc2@7e340000: 0
Loading Environment from FAT... Card did not respond to voltage select! : -110
In:    serial
Out:   vidconsole
Err:   vidconsole
Net:   eth0: ethernet@7d580000
PCIe BRCM: link up, 5.0 Gbps x1 (SSC)
starting USB...
Bus xhci_pci: probe failed, error -110
No working controllers found
Hit any key to stop autoboot:  0 
"Synchronous Abort" handler, esr 0x96000044
elr: 000000000009c1a4 lr : 0000000000091af4 (reloc)
elr: 000000003b2751a4 lr : 000000003b26aaf4
x0 : 0000000000000a30 x1 : 0000000000000a60
x2 : 702d616d642d6465 x3 : 7261687300000000
x4 : 1000000003000000 x5 : 000000000000005c
x6 : 000000003b2d32d0 x7 : 1000000002ffffd0
x8 : fffffffffffffff0 x9 : 0000000000000008
x10: 00000000ffffffd0 x11: 000000000000000a
x12: 0000000000000006 x13: 000000000001869f
x14: 000000003ae48ba0 x15: 0000000000000002
x16: 000000003b277248 x17: 99f7de22808e8223
x18: 000000003ae54da0 x19: 0000000000000031
x20: 000000003b2d2d10 x21: 000000003b2e5000
x22: 0000000000000005 x23: 000000000000000a
x24: 0000000000000000 x25: 000000003b2e5000
x26: 0000000000000000 x27: 000000003b2c74d1
x28: 000000003b2bd000 x29: 000000003ae47d10

Code: a9410803 8b130001 b2400273 f9000413 (f9000c62) 
Resetting CPU ...

resetting ...

```

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Hardware - Raspberry Pi 4B 8GB
- Raspberry Pi firmware version - c305221a Sep 3 2020 (Bootloader version: 2020-09-03 VL805: 0138a1)
- Talos version - v0.9.0-alpha.5

**Comment by smira** [comment]
I think we had success booting on 8 GiB version, but USB doesn't work. We should have USB fix in 0.10. is there new firmware available?

**Comment by frezbo** [comment]
@smira Thanks that was fast :hugs: , glad to know there's an incoming fix. I'm on the latest released firmware as of 08/05/2021. Is this an issue with the firmware or u-boot issue? Yes, the boot from SD card works, but I have other issues with it which I will link in a different issue

**Comment by smira** [comment]
There was a problem in u-boot which got fixed in the next not yet released version. We can't bump u-boot for 0.9, as it's in code freeze. But we should have new u-boot for the first 0.10 alpha

**Comment by rsmitty** [comment]
Yep, this particular issue will be fixed in the first v0.10.0 alpha. I was able to boot successfully from a USB stick late last week. I'll close this issue for now and please feel free to open a new one with any other issues you're seeing!

**Comment by andrewrynhard** [comment]
We should probably keep this open until we have the fix in a release. Just to communicate to others that this is still an issue.

**Comment by andrewrynhard** [comment]
@frezbo If you get a chance, could you test with the v0.10.0-alpha.0? Should fix this issue.

**Comment by frezbo** [comment]
@andrewrynhard I tested the `v0.10.0-alpha.0`  and I'm getting this in the console logs:

```shell
U-Boot 2021.04-rc3 (Mar 15 2021 - 11:35:33 +0000)

DRAM:  7.9 GiB
RPI 4 Model B (0xd03114)
MMC:   mmcnr@7e300000: 1, emmc2@7e340000: 0
Loading Environment from FAT... Card did not respond to voltage select! : -110
In:    serial
Out:   vidconsole
Err:   vidconsole
Net:   eth0: ethernet@7d580000
PCIe BRCM: link up, 5.0 Gbps x1 (SSC)
starting USB...
Bus xhci_pci: Register 5000420 NbrPorts 5
Starting the controller
USB XHCI 1.00
scanning bus xhci_pci for devices... Device NOT ready
   Request Sense returned 02 04 01
3 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
Hit any key to stop autoboot:  0 
Card did not respond to voltage select! : -110
Card did not respond to voltage select! : -110

Device 0: unknown device
BOOTP broadcast 1
BOOTP broadcast 2
BOOTP broadcast 3
DHCP client bound to address 192.168.10.44 (1007 ms)
*** ERROR: `serverip' not set
Cannot autoload with TFTPGET
missing environment variable: pxeuuid
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/01-dc-a6-32-ad-31-9d
*** ERROR: `serverip' not set
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/C0A80A2C
*** ERROR: `serverip' not set
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/C0A80A2
*** ERROR: `serverip' not set
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/C0A80A
*** ERROR: `serverip' not set
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/C0A80
*** ERROR: `serverip' not set
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/C0A8
*** ERROR: `serverip' not set
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/C0A
*** ERROR: `serverip' not set
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/C0
*** ERROR: `serverip' not set
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/C
*** ERROR: `serverip' not set
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/default-arm-bcm283x-rpi
*** ERROR: `serverip' not set
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/default-arm-bcm283x
*** ERROR: `serverip' not set
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/default-arm
*** ERROR: `serverip' not set
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/default
*** ERROR: `serverip' not set
Config file not found
BOOTP broadcast 1
DHCP client bound to address 192.168.10.44 (3 ms)
*** ERROR: `serverip' not set
Cannot autoload with TFTPGET
BOOTP broadcast 1
DHCP client bound to address 192.168.10.44 (3 ms)
*** ERROR: `serverip' not set
Cannot autoload with TFTPGET
U-Boot> 
```

U-boot boots fine now from the USB device. But I think it can't find the partitions.

**Comment by frezbo** [comment]
@andrewrynhard I have some new updates. I flashed `v0.10.0-alpha.1` and I got the same behavior as the logs above and was dropped into the `U-boot` prompt.

Initial boot logs:

```shell
starting USB...
Bus xhci_pci: Register 5000420 NbrPorts 5
Starting the controller
USB XHCI 1.00
scanning bus xhci_pci for devices... Device NOT ready
   Request Sense returned 02 04 01
3 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
Hit any key to stop autoboot:  0 
```

this eventually times out and loads me into the `u-boot` prompt.

 I typed in `usb info` and was able to see my USB attached NVME drive but `usb storage` did not show any results. 


```shell
U-Boot> usb info
1: Hub,  USB Revision 3.0
 - U-Boot XHCI Host Controller 
 - Class: Hub
 - PacketSize: 512  Configurations: 1
 - Vendor: 0x0000  Product 0x0000 Version 1.0
   Configuration: 1
   - Interfaces: 1 Self Powered 0mA
     Interface: 0
     - Alternate Setting 0, Endpoints: 1
     - Class Hub
     - Endpoint 1 In Interrupt MaxPacket 8 Interval 255ms

2: Hub,  USB Revision 2.10
 -  USB2.0 Hub 
 - Class: Hub
 - PacketSize: 64  Configurations: 1
 - Vendor: 0x2109  Product 0x3431 Version 4.33
   Configuration: 1
   - Interfaces: 1 Self Powered Remote Wakeup 100mA
     Interface: 0
     - Alternate Setting 0, Endpoints: 1
     - Class Hub
     - Endpoint 1 In Interrupt MaxPacket 1 Interval 12ms

3: Mass Storage,  USB Revision 3.20
 - JMicron USB to PCIE Bridge 0123456789ABCDEF
 - Class: (from Interface) Mass Storage
 - PacketSize: 512  Configurations: 1
 - Vendor: 0x152d  Product 0x0583 Version 33.2
   Configuration: 1
   - Interfaces: 1 Bus Powered 224mA
     Interface: 0
     - Alternate Setting 0, Endpoints: 2
     - Class Mass Storage, Transp. SCSI, Bulk only
     - Endpoint 1 In Bulk MaxPacket 1024
     - Endpoint 2 Out Bulk MaxPacket 1024
     - Endpoint 1 Out Bulk MaxPacket 1024
     - Endpoint 2 In Bulk MaxPacket 1024
     - Endpoint 3 In Bulk MaxPacket 1024
     - Endpoint 4 Out Bulk MaxPacket 1024

U-Boot> usb storage
No storage devices, perhaps not 'usb start'ed..?
U-Boot> 
```

After some quick search I typed in `usb reset` and and then `usb storage` and it showed my device. Then typing in `boot` booted into Talos.

```shell
U-Boot> usb reset
resetting USB...
Bus xhci_pci: Register 5000420 NbrPorts 5
Starting the controller
USB XHCI 1.00
scanning bus xhci_pci for devices... Setup ERROR: address device command for slot 1.

      USB device not accepting new address (error=80000000)
2 USB Device(s) found
       scanning usb for storage devices... 1 Storage Device(s) found
U-Boot> usb info
1: Hub,  USB Revision 3.0
 - U-Boot XHCI Host Controller 
 - Class: Hub
 - PacketSize: 512  Configurations: 1
 - Vendor: 0x0000  Product 0x0000 Version 1.0
   Configuration: 1
   - Interfaces: 1 Self Powered 0mA
     Interface: 0
     - Alternate Setting 0, Endpoints: 1
     - Class Hub
     - Endpoint 1 In Interrupt MaxPacket 8 Interval 255ms

2: Mass Storage,  USB Revision 3.20
 - JMicron USB to PCIE Bridge 0123456789ABCDEF
 - Class: (from Interface) Mass Storage
 - PacketSize: 512  Configurations: 1
 - Vendor: 0x152d  Product 0x0583 Version 33.2
   Configuration: 1
   - Interfaces: 1 Bus Powered 224mA
     Interface: 0
     - Alternate Setting 0, Endpoints: 2
     - Class Mass Storage, Transp. SCSI, Bulk only
     - Endpoint 1 In Bulk MaxPacket 1024
     - Endpoint 2 Out Bulk MaxPacket 1024
     - Endpoint 1 Out Bulk MaxPacket 1024
     - Endpoint 2 In Bulk MaxPacket 1024
     - Endpoint 3 In Bulk MaxPacket 1024
     - Endpoint 4 Out Bulk MaxPacket 1024

U-Boot> usb storage
  Device 0: Vendor: JMicron  Rev: 2102 Prod: Generic         
            Type: Hard Disk
            Capacity: 238475.1 MB = 232.8 GB (488397168 x 512)
U-Boot> 
```

typing in `boot` and successfully booting:

```shell
U-Boot> boot
Card did not respond to voltage select! : -110
Card did not respond to voltage select! : -110

Device 0: Vendor: JMicron  Rev: 2102 Prod: Generic         
            Type: Hard Disk
            Capacity: 238475.1 MB = 232.8 GB (488397168 x 512)
... is now current device
Scanning usb 0:1...
libfdt fdt_check_header(): FDT_ERR_BADMAGIC
Card did not respond to voltage select! : -110
Scanning disk mmcnr@7e300000.blk...
Disk mmcnr@7e300000.blk not ready
Card did not respond to voltage select! : -110
Scanning disk emmc2@7e340000.blk...
Disk emmc2@7e340000.blk not ready
Scanning disk usb_mass_storage.lun0...
** Unrecognized filesystem type **
** Unrecognized filesystem type **
** Unrecognized filesystem type **
** Unrecognized filesystem type **
** Unrecognized filesystem type **
Found 7 disks
** Unable to read file ubootefi.var **
Failed to load EFI variables
BootOrder not defined
EFI boot manager: Cannot load any image
Found EFI removable media binary efi/boot/bootaa64.efi
139264 bytes read in 1 ms (132.8 MiB/s)
libfdt fdt_check_header(): FDT_ERR_BADMAGIC
Booting /efi\boot\bootaa64.efi
<rest removed>
```


I suspect it could be a power issues, I'll order a new adapter and report back.  Let me know if this is an issue from `u-boot` instead if I'm on the wrong track.

**Comment by frezbo** [comment]
New updates:

I have tried a completely new power supply and seeing the same behavior. Running `usb reset` and typing in `boot` boots into Talos. I'm out of ideas what could be causing this, might be a race in boot where booting tries to occur before usb is fully initialized?.

**Comment by andrewrynhard** [comment]
@frezbo Thanks for updating with your progress. I don't have any good ideas where to go from here. Are you able to join our slack?

**Comment by frezbo** [comment]
on it, thanks :muscle:

**Comment by frezbo** [comment]
Updating the firmware on the Orico TCM-C2 USB-nVME adapters fixed this issue. Closing
