### ISSUE TITLE
Communityinvitier for Talos Slack does not work

### ISSUE THREAD

**Issue by larssb** [talos-systems/talos#4031]
### Description

When one goes to Talos Slack link your're redirected to the communityinviter service. However, a form for getting access to the Talos Slack community is nowhere to be seen.

### Environment

- Platform: Firefox v90.0.2 on MacOS Monterey

---

Exeperienced on 210807

Thank you

**Comment by andrewrynhard** [comment]
Looks like Community Inviter broke things. Thanks for the report. We will fix.

**Comment by andrewrynhard** [comment]
Fixed. If you could confirm, that would be great 👍🏻 .

**Comment by larssb** [comment]
Still broken for me. Unfortunately. I've tried in private/incognito mode in the browser as well.

**Comment by andrewrynhard** [comment]
Community inviter seems to be losing everything and I have to periodically login and configure it agin _sigh_. Try again? I just checked in incognito mode.

**Comment by windowsrefund** [comment]
It would be far better to just move the community over to IRC.

**Comment by rsmitty** [comment]
@windowsrefund did you actually hit an issue with the slackinviter here? this seems to be a pretty old issue and we haven't heard anything about it in a while. if so, do you recall what behavior you saw so we can go troubleshoot?
